version: '3'
services:

  eureka-serviceregistry:
    build: ./Eureka
    ports:
     - "8761:8761"
    tty: true

  ad-service:
    build: ./car-service
    ports:
    - "8082:8082"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  auth-service:
    build: ./authentification-service
    ports:
    - "8081:8081"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  message-service:
    build: ./message-service
    ports:
    - "8085:8085"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  rent-service:
    build: ./rent-service
    ports:
    - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  search-service:
    build: ./search-service
    ports:
    - "8084:8084"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  resource-service:
    build: ./resource-service
    ports:
    - "8086:8086"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  report-service:
    build: ./report-service
    ports:
    - "8087:8087"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  zuul:
    build: ./Zuul
    ports:
    - "8080:8080"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - ad-service
      - auth-service
      - message-service
      - rent-service
      - search-service
      - report-service
      - resource-service

  

  
